[tools]
go = "1.26.5"
node = "24.18.1"
"aqua:go-task/task" = "3.52.0"
"aqua:sqlc-dev/sqlc" = "1.31.1"
"go:github.com/wailsapp/wails/v3/cmd/wails3" = "v3.0.0-alpha2.119"

[env]
OKULA_LOG_LEVEL = "info"
