// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3112101975);
}

export function GetTheme(): $CancellablePromise<string> {
    return $Call.ByID(2906045123);
}

export function GetThemes(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1562895120);
}

export function GetTimezone(): $CancellablePromise<string> {
    return $Call.ByID(2005013849);
}

export function GetTimezones(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1271353630);
}

export function UpdateTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(1930469648, theme);
}

export function UpdateTimezone(zone: string): $CancellablePromise<void> {
    return $Call.ByID(140404320, zone);
}
