// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "../catalog/models.js";

/**
 * ClusterInstance is the DTO exposed to the frontend via Wails.
 */
export interface ClusterInstance {
    "id": string;
    "entry": catalog$0.CatalogEntry;
    "status": ClusterStatus;
    "lastSeen"?: number | null;
    "lastError"?: string | null;
}

export enum ClusterStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ClusterStatusDisconnected = "Not Connected",
    ClusterStatusConnected = "Connected",
};
