// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service for cluster operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConnectCluster makes the catalog entry the active cluster. Config errors
 * return immediately; reachability is reported via ClustersUpdated events.
 */
export function ConnectCluster(id: string): $CancellablePromise<void> {
    return $Call.ByID(4198706123, id);
}

/**
 * DisconnectCluster tears down the active cluster connection, if any.
 */
export function DisconnectCluster(): $CancellablePromise<void> {
    return $Call.ByID(1278477117);
}

export function GetClusters(): $CancellablePromise<$models.ClusterInstance[] | null> {
    return $Call.ByID(3137912110);
}

/**
 * GetNamespaces returns the active cluster's namespace names, sorted. Empty
 * when no cluster is active or the informer cache hasn't synced yet.
 */
export function GetNamespaces(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2100773101);
}
