// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ObjectDetail is the on-demand payload for a detail view. UID keys
 * follow-up calls (events) precisely across same-name recreations. Object
 * is the same object structured, for summary panels — a single fetched
 * object crossing the boundary is fine, unlike list rows.
 */
export interface ObjectDetail {
    "uid": string;
    "yaml": string;
    "object": { [_ in string]?: any } | null;
}

/**
 * ObjectEvent is one event row for a detail view, projected from a core v1
 * Event. A future cluster events page can reuse the projection.
 */
export interface ObjectEvent {
    "type": string;
    "reason": string;
    "message": string;
    "count": number;

    /**
     * Unix ms; 0 when the cluster recorded no timestamp.
     */
    "firstSeen": number;
    "lastSeen": number;
    "source": string;
}
