// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service for live resource data: it owns the resource
 * definitions, the dynamic informers, and view subscriptions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetResourceEvents lists events for an object by UID, newest first.
 * Namespace scopes the list for namespaced objects; pass "" for
 * cluster-scoped ones, whose events can land in any namespace.
 */
export function GetResourceEvents($namespace: string, uid: string): $CancellablePromise<$models.ObjectEvent[] | null> {
    return $Call.ByID(720638231, $namespace, uid);
}

/**
 * GetResourceObject fetches an object live from the cluster. Always a fresh
 * GET: informer caches are stripped/partial by design, so they can never
 * back a detail view. Namespace is ignored for cluster-scoped resources.
 */
export function GetResourceObject(key: string, $namespace: string, name: string): $CancellablePromise<$models.ObjectDetail> {
    return $Call.ByID(1215134393, key, $namespace, name);
}

/**
 * GetResourceRows returns the current projected rows for a resource type.
 * Empty until the informer's initial sync completes; a ResourceUpdated event
 * signals when to refetch.
 */
export function GetResourceRows(key: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(356876871, key);
}

/**
 * SubscribeResource registers interest in a resource type, starting its
 * informer if needed. Subscriptions made while disconnected take effect when
 * a cluster connects.
 */
export function SubscribeResource(key: string): $CancellablePromise<void> {
    return $Call.ByID(345455642, key);
}

/**
 * UnsubscribeResource releases interest in a resource type. The informer
 * lingers for a while after the last subscriber leaves, so returning to a
 * recently visited view is instant.
 */
export function UnsubscribeResource(key: string): $CancellablePromise<void> {
    return $Call.ByID(2900005223, key);
}
