// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service for live resource data: it owns the resource
 * definitions, the dynamic informers, and view subscriptions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetResourceRows returns the current projected rows for a resource type.
 * Empty until the informer's initial sync completes; a ResourceUpdated event
 * signals when to refetch.
 */
export function GetResourceRows(key: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(356876871, key);
}

/**
 * SubscribeResource registers interest in a resource type, starting its
 * informer if needed. Subscriptions made while disconnected take effect when
 * a cluster connects.
 */
export function SubscribeResource(key: string): $CancellablePromise<void> {
    return $Call.ByID(345455642, key);
}

/**
 * UnsubscribeResource releases interest in a resource type. The informer
 * lingers for a while after the last subscriber leaves, so returning to a
 * recently visited view is instant.
 */
export function UnsubscribeResource(key: string): $CancellablePromise<void> {
    return $Call.ByID(2900005223, key);
}
