// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_state.sql

package storedb

import (
	"context"
	"database/sql"
)

const getActiveClusterID = `-- name: GetActiveClusterID :one
SELECT active_cluster_id FROM app_state WHERE id = 1
`

func (q *Queries) GetActiveClusterID(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getActiveClusterID)
	var active_cluster_id sql.NullString
	err := row.Scan(&active_cluster_id)
	return active_cluster_id, err
}

const setActiveClusterID = `-- name: SetActiveClusterID :exec
UPDATE app_state SET active_cluster_id = ? WHERE id = 1
`

func (q *Queries) SetActiveClusterID(ctx context.Context, activeClusterID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, setActiveClusterID, activeClusterID)
	return err
}
