// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog_entries.sql

package storedb

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteCatalogEntry = `-- name: DeleteCatalogEntry :exec
DELETE FROM catalog_entries
WHERE id = ?
`

func (q *Queries) DeleteCatalogEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCatalogEntry, id)
	return err
}

const getCatalogEntry = `-- name: GetCatalogEntry :one
SELECT id, type, hidden, context_name, short_name, kubeconfig_path, namespace, version, distro, avatar, color, last_seen, created_at, updated_at
FROM catalog_entries
WHERE id = ?
`

func (q *Queries) GetCatalogEntry(ctx context.Context, id string) (CatalogEntry, error) {
	row := q.db.QueryRowContext(ctx, getCatalogEntry, id)
	var i CatalogEntry
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Hidden,
		&i.ContextName,
		&i.ShortName,
		&i.KubeconfigPath,
		&i.Namespace,
		&i.Version,
		&i.Distro,
		&i.Avatar,
		&i.Color,
		&i.LastSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hideAllCatalogEntriesInFolder = `-- name: HideAllCatalogEntriesInFolder :exec
UPDATE catalog_entries
SET hidden = 1,
  updated_at = ?1
WHERE hidden = 0
  AND kubeconfig_path LIKE ?2
`

type HideAllCatalogEntriesInFolderParams struct {
	UpdatedAt    time.Time
	FolderPrefix sql.NullString
}

func (q *Queries) HideAllCatalogEntriesInFolder(ctx context.Context, arg HideAllCatalogEntriesInFolderParams) error {
	_, err := q.db.ExecContext(ctx, hideAllCatalogEntriesInFolder, arg.UpdatedAt, arg.FolderPrefix)
	return err
}

const hideAllCatalogFileEntries = `-- name: HideAllCatalogFileEntries :exec
UPDATE catalog_entries
SET hidden = 1,
  updated_at = ?1
WHERE hidden = 0
`

func (q *Queries) HideAllCatalogFileEntries(ctx context.Context, updatedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, hideAllCatalogFileEntries, updatedAt)
	return err
}

const hideCatalogEntriesByPath = `-- name: HideCatalogEntriesByPath :exec
UPDATE catalog_entries
SET hidden = 1,
  updated_at = ?1
WHERE hidden = 0
  AND (
    kubeconfig_path = ?2
    OR kubeconfig_path LIKE ?3
  )
`

type HideCatalogEntriesByPathParams struct {
	UpdatedAt    time.Time
	Path         sql.NullString
	FolderPrefix sql.NullString
}

func (q *Queries) HideCatalogEntriesByPath(ctx context.Context, arg HideCatalogEntriesByPathParams) error {
	_, err := q.db.ExecContext(ctx, hideCatalogEntriesByPath, arg.UpdatedAt, arg.Path, arg.FolderPrefix)
	return err
}

const hideMissingCatalogEntriesForPath = `-- name: HideMissingCatalogEntriesForPath :exec
UPDATE catalog_entries
SET hidden = 1,
  updated_at = ?1
WHERE hidden = 0
  AND kubeconfig_path = ?2
  AND id NOT IN (/*SLICE:valid_ids*/?)
`

type HideMissingCatalogEntriesForPathParams struct {
	UpdatedAt time.Time
	Path      sql.NullString
	ValidIds  []string
}

func (q *Queries) HideMissingCatalogEntriesForPath(ctx context.Context, arg HideMissingCatalogEntriesForPathParams) error {
	query := hideMissingCatalogEntriesForPath
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	queryParams = append(queryParams, arg.Path)
	if len(arg.ValidIds) > 0 {
		for _, v := range arg.ValidIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:valid_ids*/?", strings.Repeat(",?", len(arg.ValidIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:valid_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const hideMissingCatalogEntriesInFolder = `-- name: HideMissingCatalogEntriesInFolder :exec
UPDATE catalog_entries
SET hidden = 1,
  updated_at = ?1
WHERE hidden = 0
  AND kubeconfig_path LIKE ?2
  AND kubeconfig_path NOT IN (/*SLICE:valid_paths*/?)
`

type HideMissingCatalogEntriesInFolderParams struct {
	UpdatedAt    time.Time
	FolderPrefix sql.NullString
	ValidPaths   []sql.NullString
}

func (q *Queries) HideMissingCatalogEntriesInFolder(ctx context.Context, arg HideMissingCatalogEntriesInFolderParams) error {
	query := hideMissingCatalogEntriesInFolder
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	queryParams = append(queryParams, arg.FolderPrefix)
	if len(arg.ValidPaths) > 0 {
		for _, v := range arg.ValidPaths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:valid_paths*/?", strings.Repeat(",?", len(arg.ValidPaths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:valid_paths*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const hideMissingCatalogFileEntries = `-- name: HideMissingCatalogFileEntries :exec
UPDATE catalog_entries
SET hidden = 1,
  updated_at = ?1
WHERE hidden = 0
  AND kubeconfig_path NOT IN (/*SLICE:valid_paths*/?)
`

type HideMissingCatalogFileEntriesParams struct {
	UpdatedAt  time.Time
	ValidPaths []sql.NullString
}

func (q *Queries) HideMissingCatalogFileEntries(ctx context.Context, arg HideMissingCatalogFileEntriesParams) error {
	query := hideMissingCatalogFileEntries
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UpdatedAt)
	if len(arg.ValidPaths) > 0 {
		for _, v := range arg.ValidPaths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:valid_paths*/?", strings.Repeat(",?", len(arg.ValidPaths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:valid_paths*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const listCatalogEntries = `-- name: ListCatalogEntries :many
SELECT id, type, hidden, context_name, short_name, kubeconfig_path, namespace, version, distro, avatar, color, last_seen, created_at, updated_at
FROM catalog_entries
ORDER BY context_name ASC
`

func (q *Queries) ListCatalogEntries(ctx context.Context) ([]CatalogEntry, error) {
	rows, err := q.db.QueryContext(ctx, listCatalogEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogEntry
	for rows.Next() {
		var i CatalogEntry
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Hidden,
			&i.ContextName,
			&i.ShortName,
			&i.KubeconfigPath,
			&i.Namespace,
			&i.Version,
			&i.Distro,
			&i.Avatar,
			&i.Color,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleCatalogEntries = `-- name: ListVisibleCatalogEntries :many
SELECT id, type, hidden, context_name, short_name, kubeconfig_path, namespace, version, distro, avatar, color, last_seen, created_at, updated_at
FROM catalog_entries
WHERE hidden = 0
ORDER BY context_name ASC
`

func (q *Queries) ListVisibleCatalogEntries(ctx context.Context) ([]CatalogEntry, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleCatalogEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogEntry
	for rows.Next() {
		var i CatalogEntry
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Hidden,
			&i.ContextName,
			&i.ShortName,
			&i.KubeconfigPath,
			&i.Namespace,
			&i.Version,
			&i.Distro,
			&i.Avatar,
			&i.Color,
			&i.LastSeen,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCatalogEntry = `-- name: UpsertCatalogEntry :exec
INSERT INTO catalog_entries (
  id,
  type,
  hidden,
  context_name,
  short_name,
  kubeconfig_path,
  namespace,
  version,
  distro,
  avatar,
  color,
  last_seen,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
  type = excluded.type,
  hidden = excluded.hidden,
  context_name = excluded.context_name,
  short_name = excluded.short_name,
  kubeconfig_path = excluded.kubeconfig_path,
  namespace = excluded.namespace,
  version = excluded.version,
  distro = excluded.distro,
  avatar = excluded.avatar,
  color = excluded.color,
  last_seen = excluded.last_seen,
  created_at = catalog_entries.created_at,
  updated_at = excluded.updated_at
`

type UpsertCatalogEntryParams struct {
	ID             string
	Type           string
	Hidden         int64
	ContextName    string
	ShortName      sql.NullString
	KubeconfigPath sql.NullString
	Namespace      sql.NullString
	Version        sql.NullString
	Distro         sql.NullString
	Avatar         sql.NullString
	Color          sql.NullString
	LastSeen       sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpsertCatalogEntry(ctx context.Context, arg UpsertCatalogEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertCatalogEntry,
		arg.ID,
		arg.Type,
		arg.Hidden,
		arg.ContextName,
		arg.ShortName,
		arg.KubeconfigPath,
		arg.Namespace,
		arg.Version,
		arg.Distro,
		arg.Avatar,
		arg.Color,
		arg.LastSeen,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
