// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package storedb

import (
	"context"
)

const completeFirstRun = `-- name: CompleteFirstRun :exec
UPDATE metadata SET first_run = FALSE WHERE id = 1 AND first_run = TRUE
`

func (q *Queries) CompleteFirstRun(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, completeFirstRun)
	return err
}

const getFirstRun = `-- name: GetFirstRun :one
SELECT first_run FROM metadata WHERE id = 1
`

func (q *Queries) GetFirstRun(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, getFirstRun)
	var first_run bool
	err := row.Scan(&first_run)
	return first_run, err
}

const getMetadata = `-- name: GetMetadata :one
SELECT id, first_run FROM metadata WHERE id = 1
`

func (q *Queries) GetMetadata(ctx context.Context) (Metadata, error) {
	row := q.db.QueryRowContext(ctx, getMetadata)
	var i Metadata
	err := row.Scan(&i.ID, &i.FirstRun)
	return i, err
}
