// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
	"time"
)

type CatalogEntry struct {
	ID             string
	Type           string
	Hidden         int64
	ContextName    string
	ShortName      sql.NullString
	KubeconfigPath sql.NullString
	Namespace      sql.NullString
	Version        sql.NullString
	Distro         sql.NullString
	Color          sql.NullString
	LastSeen       sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type CatalogMultiContext struct {
	ParentID string
	ChildID  string
}

type Metadata struct {
	ID       int64
	FirstRun bool
}

type Settings struct {
	ID       int64
	Theme    string
	Timezone string
}

type Watchlist struct {
	Path string
	Type sql.NullString
}
