// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package storedb

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, theme, timezone FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Settings, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Settings
	err := row.Scan(&i.ID, &i.Theme, &i.Timezone)
	return i, err
}

const getTheme = `-- name: GetTheme :one
SELECT theme FROM settings WHERE id = 1
`

func (q *Queries) GetTheme(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getTheme)
	var theme string
	err := row.Scan(&theme)
	return theme, err
}

const getTimezone = `-- name: GetTimezone :one
SELECT timezone FROM settings WHERE id = 1
`

func (q *Queries) GetTimezone(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getTimezone)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings
SET theme = ?, timezone = ?
WHERE id = 1
`

type UpdateSettingsParams struct {
	Theme    string
	Timezone string
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSettings, arg.Theme, arg.Timezone)
	return err
}

const updateTheme = `-- name: UpdateTheme :exec
UPDATE settings
SET theme = ?
WHERE id = 1
`

func (q *Queries) UpdateTheme(ctx context.Context, theme string) error {
	_, err := q.db.ExecContext(ctx, updateTheme, theme)
	return err
}

const updateTimezone = `-- name: UpdateTimezone :exec
UPDATE settings
SET timezone = ?
WHERE id = 1
`

func (q *Queries) UpdateTimezone(ctx context.Context, timezone string) error {
	_, err := q.db.ExecContext(ctx, updateTimezone, timezone)
	return err
}
