// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watchlist.sql

package storedb

import (
	"context"
	"database/sql"
)

const addToWatchlist = `-- name: AddToWatchlist :exec
INSERT OR IGNORE INTO watchlist (path, type)
VALUES (?, ?)
`

type AddToWatchlistParams struct {
	Path string
	Type sql.NullString
}

func (q *Queries) AddToWatchlist(ctx context.Context, arg AddToWatchlistParams) error {
	_, err := q.db.ExecContext(ctx, addToWatchlist, arg.Path, arg.Type)
	return err
}

const listWatchedFiles = `-- name: ListWatchedFiles :many
SELECT path FROM watchlist
WHERE type = 'file'
ORDER BY path
`

func (q *Queries) ListWatchedFiles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listWatchedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedFolders = `-- name: ListWatchedFolders :many
SELECT path FROM watchlist
WHERE type = 'folder'
ORDER BY path
`

func (q *Queries) ListWatchedFolders(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listWatchedFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFromWatchlist = `-- name: RemoveFromWatchlist :exec
DELETE FROM watchlist
WHERE path = ?
`

func (q *Queries) RemoveFromWatchlist(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, removeFromWatchlist, path)
	return err
}
