// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CatalogEntry is the DTO exposed via Wails. It uses Unix milliseconds for timestamps.
 */
export interface CatalogEntry {
    "id": string;
    "type": CatalogEntryType;
    "hidden": boolean;
    "contextName": string;
    "shortName": string;
    "kubeconfigPath": string;
    "namespace": string;
    "version": string;
    "distro": string;
    "color": string;
    "avatar": string;
    "createdAt": number;
    "updatedAt": number;
    "lastSeen": number | null;
}

export enum CatalogEntryType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CatalogEntryTypeSingle = "single",
    CatalogEntryTypeMulti = "multi",
};
