//go:build ignore

package main

import (
	"archive/zip"
	"bytes"
	_ "embed"
	"fmt"
	"io/fs"
	"log"
	"os"
	"os/exec"
	"path/filepath"
)

func main() {

	goroot, err := getGOROOT()
	if err != nil {
		log.Fatalf("failed to get GOROOT: %v", err)
	}

	zoneinfoPath := filepath.Join(goroot, "lib", "time", "zoneinfo.zip")
	outFile := os.Getenv("GOFILE")
	pkgName := os.Getenv("GOPACKAGE")

	if outFile == "" || pkgName == "" {
		log.Fatal("GOFILE and GOPACKAGE environment variables must be set by go generate")
	}

	zr, err := openZoneinfoZip(zoneinfoPath)
	if err != nil {
		log.Fatalf("failed to read zoneinfo.zip: %v", err)
	}

	if err := writeTimezoneList(outFile, pkgName, zr); err != nil {
		log.Fatalf("failed to write timezone list: %v", err)
	}

	log.Printf("Timezone list written to %s", outFile)
}

func getGOROOT() (string, error) {
	out, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return "", err
	}

	return string(bytes.TrimSpace(out)), nil
}

func openZoneinfoZip(path string) (*zip.Reader, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil {
		return nil, err
	}

	return zip.NewReader(f, info.Size())
}

func writeTimezoneList(filename, pkgName string, zr *zip.Reader) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by 'zones.gen.go'. DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "//go:generate go run zones.gen.go")
	fmt.Fprintln(f)
	fmt.Fprintf(f, "package %s\n", pkgName)
	fmt.Fprintln(f)
	fmt.Fprintln(f, "var TimeZones = []string{")

	err = fs.WalkDir(zr, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			fmt.Fprintf(f, "\t%q,\n", path)
		}
		return nil
	})
	if err != nil {
		return err
	}

	fmt.Fprintln(f, "}")
	return nil
}
